volumes:
  app_data:
  postgres_data:

services:
  app:
    build: .
    image: observations_rest
    container_name: observationsRESTContainer
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - app_data:/app_data
  postgres:
    image: postgres
    container_name: observationsDBContainer
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
