"""empty message

Revision ID: ac9cccdda39c
Revises: 
Create Date: 2024-08-11 18:46:00.799834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9cccdda39c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=True)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipmentId', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('flag', sa.Enum('valid', 'missing', name='flag'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipmentId'], ['equipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # op.add_column(
    #     'observations',
    #     sa.Column('flag', sa.Enum('valid', 'missing', name='flag'), nullable=False),
    # )
    
    op.create_index(op.f('ix_observations_equipmentId'), 'observations', ['equipmentId'], unique=False)
    op.create_index(op.f('ix_observations_flag'), 'observations', ['flag'], unique=False)
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=True)
    op.create_index(op.f('ix_observations_timestamp'), 'observations', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_timestamp'), table_name='observations')
    op.drop_index(op.f('ix_observations_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_flag'), table_name='observations')
    op.drop_index(op.f('ix_observations_equipmentId'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_table('equipments')
    # ### end Alembic commands ###
